### ISSUE TITLE
setup fails unless boto is installed

### ISSUE THREAD

**Issue by mikery** [tschellenbach/Snaptastic#19]
Even though boto is listed in setup.py requirements, install fails unless boto is installed first, because setup imports __version__, which causes Snapshotter to be imported.

Downloading/unpacking snaptastic==0.1.5
  Running setup.py egg_info for package snaptastic
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/tmp/vagrant-puppet/manifests/build/snaptastic/setup.py", line 3, in <module>
        from snaptastic import **version**, **maintainer**, **email**
      File "snaptastic/**init**.py", line 18, in <module>
        from snapshotter import Snapshotter
      File "snaptastic/snapshotter.py", line 1, in <module>
        from boto.utils import get_instance_metadata
    ImportError: No module named boto.utils
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/tmp/vagrant-puppet/manifests/build/snaptastic/setup.py", line 3, in <module>

```
from snaptastic import __version__, __maintainer__, __email__
```

  File "snaptastic/**init**.py", line 18, in <module>

```
from snapshotter import Snapshotter
```

  File "snaptastic/snapshotter.py", line 1, in <module>

```
from boto.utils import get_instance_metadata
```

ImportError: No module named boto.utils

**Comment by tschellenbach** [comment]
ok good spot, will fix!

**Comment by mikery** [comment]
Cool. I should have mentioned, it's low priority, it's not blocking 
anything I'm currently working on.

Thierry Schellenbach wrote:

**Comment by tschellenbach** [comment]
removed this problem, still have to verify if there are other problematic imports
